name: CI/CD

on: 
  push:
    branches:
        - main
        - dev

jobs:
  build:
    name: Building image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Docker hub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: drodriguez90/dotnet-ci-cd-poc:${{ github.sha }} 
  
  deployconfig:
    name: Updating prod environment
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Configuration for MAIN branch
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          echo "SERVER_HOSTNAME=${{ secrets.MAIN_SERVER_HOSTNAME }}" >> $GITHUB_ENV
          echo "SERVER_USERNAME=${{ secrets.SERVER_USERNAME }}" >> $GITHUB_ENV
          echo "SERVER_PASSWORD=${{ secrets.SERVER_PASSWORD }}" >> $GITHUB_ENV
      - name: Configuration for DEV branch
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          echo "SERVER_HOSTNAME=${{ secrets.DEV_SERVER_HOSTNAME }}" >> $GITHUB_ENV
          echo "SERVER_USERNAME=${{ secrets.SERVER_USERNAME }}" >> $GITHUB_ENV
          echo "SERVER_PASSWORD=${{ secrets.SERVER_PASSWORD }}" >> $GITHUB_ENV

  update_server:
    name: updateServer
    runs-on: ubuntu-latest
    needs: deployconfig
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ env.SERVER_HOSTNAME }}
        username: ${{ env.SERVER_USERNAME }}
        password: ${{ env.SERVER_PASSWORD }}
        script: |
          docker image pull drodriguez90/dotnet-ci-cd-poc:${{ github.sha }}
          docker container stop mywebapp
          docker container prune -f
          docker run -d --name mywebapp --restart unless-stopped -p 80:80 -p 443:443 drodriguez90/dotnet-ci-cd-poc:${{ github.sha }}
          docker image prune -f   