name: CI/CD

on: 
  push:
    branches:
        - feature/*

jobs:
  build:
    name: feature pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: echo "feature"